language: node_js
sudo: false
node_js:
  - "10.13.0"
install:
  - npm install -g jasmine
  - npm install -g istanbul
  - npm install -g codecov
  - npm install
script:
  - npm test
  - npm run report-coverage